[var name:"randomSeed" value:1 /]

[section]

[CoverImage img:"bjbxvz-uyc-jordan-mcqueen.jpg" heightPercent:95]
  [Header
    title:"Standard Error of Measurement"
    author:"Center for Assessment"
    authorLink:"http://nciea.org/"
  /]
[/CoverImage]

Well hello there! To create a "screen" of text you can wrap
blocks in `[waypoint]Text here[/waypoint]` tags.

If you want the text vertically centered
on the page use `[waypoint center:true]` for the opening tag.

[var name:"slide" value:"images/01.png" /]

[Feature]
  [FeatureContent]
    [FeatureAside]
      [img src:slide /]
    [/FeatureAside]
  [/FeatureContent]

  [TextBlock onEnterView:`slide = "images/01.png"` /]
  [TextBlock onEnterView:`slide = "images/02.png"` /]
  [TextBlock onEnterView:`slide = "images/03.png"` /]
  [TextBlock onEnterView:`slide = "images/04.png"` /]
  [TextBlock onEnterView:`slide = "images/05.png"` /]
  [TextBlock onEnterView:`slide = "images/06.png"` /]
  [TextBlock onEnterView:`slide = "images/07.png"` /]
  [TextBlock onEnterView:`slide = "images/08.png"` /]
  [TextBlock onEnterView:`slide = "images/09.png"` /]
  [TextBlock onEnterView:`slide = "images/10.png"` /]
[/Feature]

[waypoint]
The waypoint component is extremely basic right now
and will evolve. We will also likely create a custom
chart to sit over there on the side. The one currently there does not change at the moment.

This slider will update the `randomSeed` var though.

Update it: [Range min:0 max:50 value:randomSeed /]

Scrolling to the next waypoint will set `randomSeed` to 25.
[/waypoint]

[waypoint center:true onEnteredView:`randomSeed = 25`]
One more waypoint for good measure
[/waypoint]

[/section]
